export const OperationTypesEnum = {
    ILIKE: 'ILIKE',
    LIKE: 'LIKE',
    IN: 'IN',
    BETWEEN: 'BETWEEN',
    IS: 'IS',
    NOT: 'NOT',
    NULL: 'NULL',
    TRUE: 'TRUE',
    FALSE: 'FALSE',
    EQUAL: '=',
    NOT_EQUAL: '!=',
    GREATER: '>',
    GREATER_EQUAL: '>=',
    LESS: '<',
    LESS_EQUAL: '<=',
} as const;
